### ISSUE TITLE
Typo in locales.json 

### ISSUE THREAD

**Issue by rcgary** [jsonrates/api-benchmark#1]
Not sure if this a good place for feedback, let me know if I can send this in another place 

In `http://jsonrates.com/currencies.json`
```
  "AZN": "Azerbaijan New Manat",
```
But in `http://jsonrates.com/locales.json`
```
    "az_AZ": {
    "name": "Azerbaijani (Azerbaijan)",
    "currency": "AZM"
  },
```
Should be **AZN** not **AZM**
I think this is a typo.

**Comment by jamsouf** [comment]
Thanks!

AZM was the old currency of Azerbaijan.
Fixed.
